run-single-serial-tests:
	go test -v -p 1 -count=1 ./tests/serial/singletests/...

run-single-parallel-tests:
	go test -v -p 1 -count=1 ./tests/parallel/singletests/...

run-serial-tests:
	go test -v -p 1 -count=1 ./tests/serial/...

run-parallel-tests:
	go test -v -p 1 -count=1 ./tests/parallel/...

run-all-tests-in-1-program:
	go test -v -p 1 -count=1 ./tests/...

run-all-tests-in-4-programs:
	go test -v -p 4 -count=1 ./tests/...

run-serial-tests-in-1-program:
	go test -v -p 1 -count=1 ./tests/serial/...

run-serial-tests-in-2-programs:
	go test -v -p 2 -count=1 ./tests/serial/...
	